# Generated by Django 3.0.2 on 2020-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Cname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
