# Generated by Django 3.0.2 on 2020-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
