# Generated by Django 3.0.2 on 2020-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Dp',
            field=models.ImageField(blank=True, upload_to='user_pic'),
        ),
    ]
