# Generated by Django 3.0.2 on 2020-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0005_auto_20200213_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
