# Generated by Django 3.0.2 on 2020-02-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0007_auto_20200214_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Discounted_price', models.FloatField()),
                ('descriptions', models.TextField()),
                ('Image', models.ImageField(default='', upload_to='images/')),
                ('Cname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appecom.Category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
