# Generated by Django 3.0.2 on 2020-02-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0008_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
